import math

TILESIZE  = 64 
ROWS = 15
COLOUMN = 20 

WINDOW_WIDTH = COLOUMN * TILESIZE
WINDOW_HIGHT = ROWS * TILESIZE

FIELD_OF_VIEW = math.radians(60)
# PI_FILED_OF_VIEW = 60*(math.pi / 180)

# THE WIDTH OF EACH RECTANGLE (resolution) 
RES = 4
NUM_RAYS = WINDOW_WIDTH / RES

